Repository NASA-AMMOS/BSL, pull requests merged in 2025-08, with the labels that each got.

#5 Use closer-to-native RPM building
  .github/workflows/build-test.yaml
  .github/workflows/docs.yaml
  .github/workflows/packages.yaml
  build.sh
Labels: enhancement

#27 Rebase Crypto Test fixtures
  src/BSLConfig.h.in
  src/CryptoInterface.h
  src/crypto/CryptoInterface.c
  src/security_context/BCB_AES_GCM.c
  src/security_context/DefaultSecContext_Private.h
  test/bsl_test_utils.c
  test/bsl_test_utils.h
  test/test_BackendSecurityContext.c
  test/test_DefaultSecurityContext.c
Labels: enhancement

#31 Adding spellcheck to the API docs and fix various typos found
  .github/workflows/docs.yaml
  .gitignore
  docs/api/CMakeLists.txt
  docs/api/Developer_Guide.md
  docs/api/Doxyfile.in
  docs/api/InterfaceSpec.md
  docs/api/UserGuide.md
  docs/api/dictionary.txt
  docs/api/footer.html
  docs/api/header.tex
  docs/api/index.html
  docs/api/mainpage.md
  docs/api/sort_dictionary.sh
  docs/api/spellcheck.xsl
  src/BPSecLib_Private.h
  src/BPSecLib_Public.h
  src/CryptoInterface.h
  src/backend/AbsSecBlock.h
  src/backend/LoggingStderr.c
  src/backend/PublicInterfaceImpl.h
  src/backend/SecResult.h
  src/backend/SecurityResultSet.c
  src/backend/SecurityResultSet.h
  src/mock_bpa/bsl_mock_bpa.c
  src/mock_bpa/bsl_mock_bpa_eid.c
  src/mock_bpa/bsl_mock_bpa_eid.h
  src/mock_bpa/bsl_mock_bpa_eidpat.h
  src/policy_provider/SamplePolicyProvider.h
  src/security_context/DefaultSecContext_Private.h
  test/bsl_test_utils.c
  test/bsl_test_utils.h
  test/test_BackendPolicyProvider.c
  test/test_BackendSecurityContext.c
  test/test_DefaultSecurityContext.c
Labels: documentation

#30 BCB Sourcing Fixes & PP Finalize API
  mock-bpa-test/_generate_simple_bundles.py
  mock-bpa-test/requirements_tests.py
  src/BPSecLib_Private.h
  src/CMakeLists.txt
  src/backend/AbsSecBlock.c
  src/backend/AbsSecBlock.h
  src/backend/PolicyProvider.c
  src/backend/PublicInterfaceImpl.c
  src/backend/SecOperation.c
  src/backend/SecurityContext.c
  src/mock_bpa/bsl_mock_bpa_decode.c
  src/mock_bpa/bsl_mock_bpa_eidpat.c
  src/mock_bpa/bsl_mock_bpa_eidpat.h
  src/mock_bpa/bsl_mock_bpa_policy_config.c
  src/mock_bpa/bsl_mock_bpa_policy_config.h
  src/mock_bpa/mock_bpa.c
  src/mock_bpa/mock_bpa_ctr.c
  src/mock_bpa/mock_bpa_ctr.h
  src/policy_provider/SamplePolicyProvider.c
  src/policy_provider/SamplePolicyProvider.h
  src/security_context/BCB_AES_GCM.c
  src/security_context/DefaultSecContext_Private.h
  src/security_context/rfc9173.h
  test/CMakeLists.txt
  test/bsl_test_utils.c
  test/test_BackendPolicyProvider.c
  test/test_DefaultSecurityContext.c
  test/test_MockBPA_Codecs.c
  test/test_MockBPA_EID.c
  test/test_PublicInterfaceImpl.c
  test/test_SecurityTypes.c
  test/test_mock_bpa_ctr.c
Labels: bug

#34 Fixing the lack of PDF output for API docs
  .github/workflows/docs.yaml
  docs/api/CMakeLists.txt
  docs/api/Doxyfile.in
Labels: documentation

#43 Fixing wakeup upon interrupt signal
  .github/workflows/build-test.yaml
  mock-bpa-test/helpers/runner.py
  mock-bpa-test/pytest.ini
  mock-bpa-test/test_bpa.py
  src/mock_bpa/mock_bpa.c
Labels: bug

#50 Fix CMake BSLConfig
  CMakeLists.txt
  src/BPSecLib_Public.h
  src/BSLConfig.h.in
  src/CMakeLists.txt
Labels: bug

#80 Multiple Policy Provider Support
  src/BPSecLib_Private.h
  src/BPSecLib_Public.h
  src/backend/PolicyProvider.c
  src/backend/PublicInterfaceImpl.c
  src/backend/PublicInterfaceImpl.h
  src/backend/SecurityAction.c
  src/backend/SecurityAction.h
  src/mock_bpa/mock_bpa.c
  src/policy_provider/SamplePolicyProvider.c
  src/policy_provider/SamplePolicyProvider.h
  test/bsl_test_utils.h
  test/test_BackendPolicyProvider.c
  test/test_PublicInterfaceImpl.c
Labels: bug, CRIT-1

#91 More Key-wrapping rework | Add key-wrapping ability to BIB ctx
  docs/api/dictionary.txt
  docs/api/refs.bib
  mock-bpa-test/_generate_simple_bundles.py
  src/BPSecLib_Private.h
  src/CryptoInterface.h
  src/crypto/CryptoInterface.c
  src/mock_bpa/policy_config.c
  src/security_context/BCB_AES_GCM.c
  src/security_context/BIB_HMAC_SHA2.c
  src/security_context/DefaultSecContext.h
  src/security_context/DefaultSecContext_Private.h
  test/bsl_test_utils.c
  test/bsl_test_utils.h
  test/test_BackendSecurityContext.c
  test/test_CryptoInterface.c
  test/test_DefaultSecurityContext.c
  test/test_MockBPA_Codecs.c
  test/test_MockBPA_EID.c
  test/test_PublicInterfaceImpl.c
  test/test_mock_bpa_ctr.c
Labels: CRIT-2

#94 Fix logging errors introduced in #86
  src/policy_provider/SamplePolicyProvider.c
Labels: bug

#95 Crypto Concurrency Tests
  src/crypto/CryptoInterface.c
  test/test_CryptoInterface.c
Labels: sustainment

#96 Make the BSL use in Mock BPA thread safe
  build.sh
  docs/api/dictionary.txt
  mock-bpa-test/helpers/runner.py
  mock-bpa-test/test_bpa.py
  src/BPSecLib_Private.h
  src/BPSecLib_Public.h
  src/backend/HostInterface.c
  src/backend/PublicInterfaceImpl.c
  src/mock_bpa/CMakeLists.txt
  src/mock_bpa/MockBPA.h
  src/mock_bpa/agent.c
  src/mock_bpa/agent.h
  src/mock_bpa/bundle.c
  src/mock_bpa/bundle.h
  src/mock_bpa/ctr.h
  src/mock_bpa/decode.h
  src/mock_bpa/eid.c
  src/mock_bpa/eid.h
  src/mock_bpa/encode.h
  src/mock_bpa/mock_bpa.c
  src/mock_bpa/policy_config.c
  src/mock_bpa/policy_config.h
  src/mock_bpa/policy_registry.c
  src/mock_bpa/policy_registry.h
  test/fuzz_dynamic_asb_cbor.cpp
  test/fuzz_mock_bpa_bpv7_cbor.cpp
  test/fuzz_mock_bpa_eid_cbor.cpp
  test/fuzz_mock_bpa_eid_uri.cpp
  test/fuzz_mock_bpa_eidpat_text.cpp
  test/test_BackendPolicyProvider.c
  test/test_BackendSecurityContext.c
  test/test_DefaultSecurityContext.c
  test/test_MockBPA_Codecs.c
  test/test_MockBPA_EID.c
  test/test_PublicInterfaceImpl.c
  test/test_SamplePolicyProvider.c
  test/test_SecurityTypes.c
  test/test_mock_bpa_ctr.c
Labels: bug, CRIT-2
